name: Terraform CI-CD

on:
  push:
    branches:
      - main
      - 'feature/**'

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:

  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./enviornments/dev

    steps:

      # Checkout
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Azure Login
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Terraform Format
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # Terraform Init
      - name: Terraform Init
        run: terraform init

      # Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Upload Plan
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: enviornments/dev/tfplan


  terraform-apply:
    name: Terraform Apply
    needs: terraform-plan

    runs-on: ubuntu-latest

    # Manual approval is configured on this environment
    environment:
      name: production

    defaults:
      run:
        working-directory: ./enviornments/dev

    steps:

      # Checkout
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Azure Login
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Terraform Init
      - name: Terraform Init
        run: terraform init

      # Download Plan
      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: enviornments/dev

      # Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan